### PR TITLE
Make things easier when getting started

### PR DESCRIPTION
**Pull request by martinengelcke**
- Update requirements: Sonnet requires some packages to be installed via pip that are not included automatically. Maybe remove Sonnet from the example to minimise dependencies?
- Remove example checkpoints from repository: Not sure they need to be included in the repo and they take up quite a bit of space.
- Move example configs into example directory, update paths in example: I would propose having all the files related to the example reside in that directory. I also had problems before with some paths not being found. Here I assume that the current working directory is forge/examples and all paths are relative to that.

### CODE REVIEW

**Comment by akosiorek** [comment]
- we can remove Sonnet and just use pure tf; otherwise I'm not sure the format for comments you used in requirements.txt will work
- I think it's important to keep a checkpoint in the repo to show that some of the examples actually work; we could make the model (and therefore the checkpoint) much smaller
- I like having all example files in example folders
- My idea was that the working dir is in the `forge` folder, not in `examples`, hence the paths I used. Do you think it's better to have it in `examples`?

**Comment by martinengelcke** [comment]
> * we can remove Sonnet and just use pure tf; otherwise I'm not sure the format for comments you used in requirements.txt will work
Sounds good. Didn't realise there is a special format for the requirements.
> * I think it's important to keep a checkpoint in the repo to show that some of the examples actually work; we could make the model (and therefore the checkpoint) much smaller
I see your point and no problem keeping the checkpoints if they are smaller.
> * I like having all example files in example folders
:)
> * My idea was that the working dir is in the `forge` folder, not in `examples`, hence the paths I used. Do you think it's better to have it in `examples`?
I tend to assume the working dir is equal to the location of the script being run unless specified otherwise. Though this is unlikely to be a sensible strategy in all cases. The problem would not exist with absolute paths, but in practice relative paths are much nicer when prototyping so it makes sense to stick with them. When using using Forge for an outside project, the working dir will be the project directory and never the Forge directory itself. Hence, I would rather make examples the working dir. This doesn't matter too much in the end though, so if you feel strongly otherwise I would simply add a note to make explicit what the working dir should be.

**Comment by martinengelcke** [comment]
> * we can remove Sonnet and just use pure tf; otherwise I'm not sure the format for comments you used in requirements.txt will work

Sounds good. Didn't realise there is a special format for the requirements.

> * I think it's important to keep a checkpoint in the repo to show that some of the examples actually work; we could make the model (and therefore the checkpoint) much smaller

I see your point and no problem keeping the checkpoints if they are smaller.

> * I like having all example files in example folders

:)

> * My idea was that the working dir is in the `forge` folder, not in `examples`, hence the paths I used. Do you think it's better to have it in `examples`?

I tend to assume the working dir is equal to the location of the script being run unless specified otherwise. Though this is unlikely to be a sensible strategy in all cases. The problem would not exist with absolute paths, but in practice relative paths are much nicer when prototyping so it makes sense to stick with them. When using using Forge for an outside project, the working dir will be the project directory and never the Forge directory itself. Hence, I would rather make examples the working dir. This doesn't matter too much in the end though, so if you feel strongly otherwise I would simply add a note to make explicit what the working dir should be.

**Comment by martinengelcke** [comment]
> * we can remove Sonnet and just use pure tf; otherwise I'm not sure the format for comments you used in requirements.txt will work

Sounds good. Didn't realise there is a special format for the requirements.

> * I think it's important to keep a checkpoint in the repo to show that some of the examples actually work; we could make the model (and therefore the checkpoint) much smaller
I see your point and no problem keeping the checkpoints if they are smaller.

> * I like having all example files in example folders

:)

> * My idea was that the working dir is in the `forge` folder, not in `examples`, hence the paths I used. Do you think it's better to have it in `examples`?

I tend to assume the working dir is equal to the location of the script being run unless specified otherwise. Though this is unlikely to be a sensible strategy in all cases. This problem would not exist with absolute paths, but in practice relative paths are much nicer when prototyping so it makes sense to stick with them. When using Forge for an outside project, the working dir will be the project directory and never the Forge directory itself. Hence, I would rather make examples the working dir. This doesn't matter too much in the end though, so if you feel strongly otherwise I would simply add a note to make explicit what the working dir should be.

**Comment by martinengelcke** [comment]
> * we can remove Sonnet and just use pure tf; otherwise I'm not sure the format for comments you used in requirements.txt will work

Sounds good. Didn't realise there is a special format for the requirements.

> * I think it's important to keep a checkpoint in the repo to show that some of the examples actually work; we could make the model (and therefore the checkpoint) much smaller

I see your point and no problem keeping the checkpoints if they are smaller.

> * I like having all example files in example folders

:)

> * My idea was that the working dir is in the `forge` folder, not in `examples`, hence the paths I used. Do you think it's better to have it in `examples`?

I tend to assume the working dir is equal to the location of the script being run unless specified otherwise. Though this is unlikely to be a sensible strategy in all cases. This problem would not exist with absolute paths, but in practice relative paths are much nicer when prototyping so it makes sense to stick with them. When using Forge for an outside project, the working dir will be the project directory and never the Forge directory itself. Hence, I would rather make examples the working dir. This doesn't matter too much in the end though, so if you feel strongly otherwise I would simply add a note to make explicit what the working dir should be.

**Comment by martinengelcke** [comment]
Probably need to update some of the file links in the ReadMe because some file paths have changed. I am not sure how to get the right links though without having merged into master first.

**Comment by martinengelcke** [comment]
Will clean things up and create a new PR.

**Pull request closed without merging**
