### PR TITLE
Print function that writes to both command line and text file

### PR DESCRIPTION
**Pull request by martinengelcke**
Add an fprint function (shorthand for either file print or Forge print) that works like print() but also appends the input string to an experiment specific text file.

(See issue #2 )

### CODE REVIEW

**Comment by martinengelcke** [comment]
Any thoughts @akosiorek ?

**Comment by akosiorek** [comment]
I'd suggest using logging functions from absl/tf and setting log file directory to experiment folder; this can be done in init checkpoint func.

**Comment by martinengelcke** [comment]
What is the benefit of using absl?

**Comment by akosiorek** [comment]
It's tested, very efficient, multi-threaded, allows lots of configuration etc - usual benefits from a packaged developed by Google

**Comment by martinengelcke** [comment]
Ok. I am not familiar with absl and would propose to merge as is and extend later if needed. Or do you have capacity to do this?

**Comment by akosiorek** [comment]
ok

**Pull request merged**
